.PHONY: clean All

All:
	@echo "----------Building project:[ project-1 - Debug ]----------"
	@cd "project-1" && "$(MAKE)" -f  "project-1.mk"
clean:
	@echo "----------Cleaning project:[ project-1 - Debug ]----------"
	@cd "project-1" && "$(MAKE)" -f  "project-1.mk" clean
